FROM registry.access.redhat.com/ubi9/go-toolset:latest as builder
ENV sourcesdir /go/src/github.com/microservices-demo/user/
ENV MONGO_HOST mytestdb:27017
ENV HATEAOS user
ENV USER_DATABASE mongodb

USER 0
RUN mkdir -p /go/src/github.com/microservices-demo/ \
    && cd /go/src/github.com/microservices-demo/ \
    && git clone https://github.com/ocp-power-demos/sock-shop-user.git \
    && mv sock-shop-user user/

# Decided to split the steps here to avoid rebuilding/cloning needlessly.

RUN cd /go/src/github.com/microservices-demo/user && rm -f go.mod \
    && go mod init github.com/microservices-demo/user \
    && go mod tidy && GOOS=linux go build . && find / -name user -type f
USER 1001

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

ENV     SERVICE_USER=myuser \
        SERVICE_UID=10001 \
        SERVICE_GROUP=mygroup \
        SERVICE_GID=10001

RUN microdnf update -y \
    && microdnf install -y nc tzdata openssl ca-certificates fontconfig glibc-langpack-en gzip tar findutils shadow-utils \
    && groupadd -r -g ${SERVICE_GID} ${SERVICE_GROUP} \
    && useradd -r -u ${SERVICE_UID} -g ${SERVICE_GROUP} -m -d /home/${SERVICE_USER} -s /sbin/nologin ${SERVICE_USER} \
    && mkdir -p /opt

WORKDIR /opt
EXPOSE 8080
COPY --from=builder /go/src/github.com/microservices-demo/user/user /opt/

RUN     chmod +x /opt/user && \
        chown -R ${SERVICE_USER}:${SERVICE_GROUP} /opt/user

USER ${SERVICE_USER}

CMD ["/opt/user", "-port=8080"]